language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "PmS8xQq4Jm9rXhSZPLazI8/8+hMHpE/FBZk/cjbNAvvL0RDkm9FPuRTNvFM3NIft0ARMXKQNbCNgDnkHyW5kyvfpYlt4fN8w2Dln7SZoUZGwf
3o2e2nt3o5e4bL/dgtoVvnTWTb9+cxCR8YKr1dcX3/l2kOPotwbsHz0EbqPow4G134l3fatYBjcYwcSJ14GjEF6o4R0aUrizLEUrZfY4eo9hV056drhaZFIw
T5l2Pik4TPOdtJDd9tcQesCV3yoeWLToLl1Py/8EPwGAWaru3XRhjwFMfxJt9Qgrf9JWl5+n+DxQNO+YdTR/1/WMoav/34IXPZw0REtKigeekVslJEzHp4uf
LK3QB5juy9W7NxlXikpL10BVa4DwsEn7bO4zajMvdwgiHX8Truf2WPz0WY7tmr/WFxTWQc67KP6QmeAmUd3GFjvpr/iDOhixSabP5zjeiPZpBgyUnfs0VYzT
LCqX2GzST8fwqevW8l11hdw7xFDOoe8D+1znbclV4nkpepsGdxJZCVsJp0rxxyRhtnv9SdkI8XLcFWZGLK4kiHD+dUzWucUDW0iS8uOL236c9bpcDkL0UMxA
V63Is10AlAkVXKxiiOanyf7T3xMJ+kTIDE8hJ5Fbpl8vHVEovyjflvcoUcuYXnMmp/V8nrfzpVnYm6NnP6CcPDVATHgoF4="

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps

script:
  - mvn test -B

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: oraclejdk8
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - stage: test
      jdk: oraclejdk11
    - stage: test
      jdk: openjdk11
